services:
  postgres:
    container_name: postgres-db
    image: 'postgres:17.4-alpine3.21'
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=oauth2'
      - 'POSTGRES_USER=yu71'
      - 'POSTGRES_PASSWORD=53cret'
    ports:
      - '5433:5432'
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 53cret
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
